# Generated by Django 4.2.3 on 2023-08-23 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.ManyToManyField(to='quiz.difficulty'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.questiontype'),
            preserve_default=False,
        ),
    ]
