# Generated by Django 4.2.3 on 2023-08-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.difficulty'),
            preserve_default=False,
        ),
    ]
