# Generated by Django 4.2.3 on 2023-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_personne_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='points',
            field=models.IntegerField(blank=True),
        ),
    ]
